### PR TITLE
Change jps command to include more arguments and make the regex match…

### LINKED ISSUE #16: Wrong PID when multiple instances running
Currently sbt-dynamodb calls `jps` and searches for a running instance of `DynamoDBLocal.jar` to determine the PID.

This can be a problem when trying to call `stopDynamodbLocal` when there are multiple instances of DynamoDBLocal running on different ports (e.g., started by a different sbt project/subproject on the same machine), since the wrong dynamo PID ends up being terminated.

### PR DESCRIPTION
**Pull request by jschlather**
… against file path and port, to ensure the correct process is killed.

Should resolve #16.

### CODE REVIEW

File: src/test/scala/com/localytics/sbt/dynamodb/DynamoDBLocalUtilsTest.scala [hunk 1]
```diff
@@ -9,14 +10,30 @@ class DynamoDBLocalUtilsTest extends FunSpec with Matchers {
...
-          |51449
+          |92433 sun.tools.jps.Jps -ml
+          |88818 /usr/local/Cellar/sbt/0.13.7/libexec/sbt-launch.jar
+          |88421 /usr/local/Cellar/sbt/0.13.7/libexec/sbt-launch.jar
+          |5895 com.intellij.database.remote.RemoteJdbcServer com.mysql.jdbc.Driver
+          |92431 /Users/person/code/repository/aws-mocks/dynamo-db/DynamoDBLocal.jar -port 8000 -inMemory -sharedDb
+          |74414 /usr/local/Cellar/sbt/0.13.7/libexec/sbt-launch.jar
         """.stripMargin
+      val baseDir = new File("/Users/person/code/repository/aws-mocks/dynamo-db/")
+      DynamoDBLocalUtils.extractDynamoDBPid(jpsOutput, 8000, baseDir) should equal(Some("92431"))
```
Comment (jschlather) [inline src/test/scala/com/localytics/sbt/dynamodb/DynamoDBLocalUtilsTest.scala]: These tests are going to fail on Windows, I think the code should still work cross platform. Not sure how concerned we are with these tests working cross platform.

Comment (bdarfler) [inline src/test/scala/com/localytics/sbt/dynamodb/DynamoDBLocalUtilsTest.scala]: Sounds fine to me we all develop on mac and if/when we add CI it will be on linux. The windows support only came through via a PR a while back.

**Comment by bdarfler** [comment]
:shipit: @jschlather do you want to do the honors of releasing or shall I?

**Comment by jschlather** [comment]
I have no preference. If you want to that's fine, otherwise I can do in ~45
minutes.

**Comment by bdarfler** [comment]
I got it

**Comment by williamho** [comment]
Wow, that got resolved a lot quicker than I expected. Thanks! 👍

**Comment by bdarfler** [comment]
Just how we do! Glad to exceed your expectations. Hope this plugin is proving to be helpful!
